### ISSUE TITLE
Clearing my changeset verification does not remove tags 

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#149] opened 2017-07-05 14:03 UTC
1. Verify a changeset as bad
2. Add severity tags
3. Clear verification

The severity tags do not clear as expected.

<img width="320" alt="screen shot 2017-07-05 at 7 31 26 pm" src="https://user-images.githubusercontent.com/126868/27867875-97f4ec2e-61b8-11e7-8dc5-5655a03a7220.png"><br>
[osmcha](https://osmcha.mapbox.com/changesets/42434144/?filters=%7B%22users%22%3A%5B%7B%22label%22%3A%22Jeremy%20Quanno%22%2C%22value%22%3A%22Jeremy%20Quanno%22%7D%5D%7D)

**Comment by ajithranka** [comment] 2017-07-06 11:29
cc: @kepta @rasagy @batpad

**Comment by ajithranka** [comment] 2017-07-06 11:30
+ @manoharuss

**Comment by manoharuss** [comment] 2017-07-07 03:33
+1 
This was the case with the old instance of OSMCha as well but I did not bring it up as we were working on OSMCha v2. Clearing of a review probably means that the intial review was probably mistaken and needs to be changed (or the initial impression is not right anymore). So the tag's get outdated when the review is cleared. 

Lets clear tags as well when we clear review.

cc @kepta @ajithranka @rasagy @geohacker @batpad

**Comment by kepta** [comment] 2017-07-07 04:16
@batpad reading the comments I feel this should be a rule on the backend side. 
No changeset can have a tag if it checked. 
What do you think ?

**Comment by rasagy** [comment] 2017-07-11 11:45
Holding on to this till we can understand how to approach tags & review as being discussed in #152.

**Comment by tridip1931** [comment] 2018-01-20 11:24
duplicate of #152 . Closing this.

**Closed by tridip1931** 2018-01-20 11:24 UTC
