### ISSUE TITLE
Improvement to filter: NOT <user>

### ISSUE THREAD

**Issue by muralito** [mapbox/osmcha-frontend#160] opened 2017-07-14 18:45 UTC
I would like to see a checkbox in the user list (or something like that) to exclude users, so I can exclude users I trust (like me ;-)) and others that always behave well.

**Comment by kepta** [comment] 2017-07-15 04:07
hey @muralito have a look here https://github.com/mapbox/osmcha-frontend/issues/127.

**Comment by kepta** [comment] 2017-07-19 05:47
Closing ticket duplicate of #127

**Closed by kepta** 2017-07-19 05:47 UTC
