### ISSUE TITLE
Safari Rendering with overlapping in left panel

### ISSUE THREAD

**Issue by roadgeek** [mapbox/osmcha-frontend#218] opened 2017-10-22 16:47 UTC
<img width="1280" alt="osmcha-leftpanelsafari9 1 3 -render" src="https://user-images.githubusercontent.com/10214616/31864120-503d0876-b726-11e7-948e-19cf45106057.png">

## I'm submitting a _bug report.
Safari rendering has overlap with changesets and title.

## What  is the current behaviour, (attach relevant screenshots) ?
Attached

## What  is the expected behaviour ?
no overlap

## When does this occur ?
Always

## How do we replicate the issue ?

1. Opened OSMCha

## Please tell us about your environment:
Safari 9.1.3 OS X 10.11.6

**Comment by willemarcel** [comment] 2018-03-25 21:21
@roadgeek I tested on the Safari 11.0.3 and this bug is not occurring.

@tridip1931 do you have some opinion about what we could do about it?

**Comment by tridip1931** [comment] 2018-04-03 10:37
@roadgeek @willemarcel 
I cannot reproduce this bug in Safari 11.0.1

Initially my hunch was bug was due to inconsistent z-index, looks this was fixed. Are we good to close?

**Comment by willemarcel** [comment] 2018-04-03 12:13
thanks, closing...

**Closed by willemarcel** 2018-04-03 12:13 UTC
Labels: [Skill] CSS/Sass, [Type] Bug
