### ISSUE TITLE
filter by tags

### ISSUE THREAD

**Issue by canfe** [mapbox/osmcha-frontend#519] opened 2021-02-15 13:07 UTC
It would be useful to be able to filter changesets where there is at least one specific tag and value pair.

Example: building=yes

**Comment by fansanelli** [comment] 2021-02-16 06:15
Possible duplicate of #344 . But it's increasing the number of people whom would like to see this feature implemented. I recently read on Italian mailing list too and it's a show stopper for someone. Imagine that you work on specific tasks on a large scale and you only care about certain tags being added, removed or changes to objects with those tags... Please let us know what you need to develop this feature, we can give some help.
Many thanks
Cheers
Francesco

**Comment by willemarcel** [comment] 2022-05-05 23:12
Duplication of #344, but the good news is that we are going to implement it soon.

**Closed by willemarcel** 2022-05-05 23:12 UTC
