### ISSUE TITLE
Show aggregate review stats for filter results

### ISSUE THREAD

**Issue by planemad** [mapbox/osmcha-frontend#234] opened 2017-12-05 13:21 UTC
## *Brief Description*
While trying to review [Pokemon mapping](https://osmcha.mapbox.com/changesets/54339099?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222017-11-30%22%2C%22value%22%3A%222017-11-30%22%7D%5D%2C%22date__lte%22%3A%5B%7B%22label%22%3A%222017-12-05%22%2C%22value%22%3A%222017-12-05%22%7D%5D%2C%22reasons%22%3A%5B%7B%22label%22%3A%22New%20mapper%22%2C%22value%22%3A40%7D%5D%2C%22comment%22%3A%5B%7B%22label%22%3A%22pokemon%22%2C%22value%22%3A%22pokemon%22%7D%5D%7D) in the past week, i'm trying to get a sense of how many changesets are good vs bad, but its hard to count these from the existing interface.

## What is the motivation / use case for this feature?

To be able to quickly see review statistics for the result of any filter. This can help:
- Understand how many good vs bad changesets are there for any filter
- How many changesets require review and act as a task queue

## Other Information / context:

Ugly mockup:

<img width="314" alt="osm_changeset_analyzer_and_maintain_list_of_harmful_osm_edits_ _issue__13_ _mapbox_map-validation" src="https://user-images.githubusercontent.com/126868/33609075-bbb33740-d9ec-11e7-84d9-2a97fef78cb1.png">

**Comment by tridip1931** [comment] 2017-12-11 06:46
This design could be meaningful. I believe OSM users come to OSMCha with some objective and would want to filter the information aligned with that specific objective in mind. I'd like to do more research on this.

**Comment by rasagy** [comment] 2017-12-11 06:49
Flagging that there was a relevant conversation on this thread that we could revive as well: https://github.com/mapbox/osmcha-frontend/issues/200

Basically, use the right panel to show stats based on the filtered query instead of the placeholder splash screen. I completely forgot about my discussion with @zlavergne at SOTM about this, let me update that ticket with what we discussed.

**Comment by tridip1931** [comment] 2018-01-20 11:06
Duplicate of #200 Closing this.

**Closed by tridip1931** 2018-01-20 11:06 UTC
Labels: [Skill] Research, [Status] Idea, [Type] Enhancement
